version: '3'

services:
  frontend:
    build:
      context: ./micro-blog_micro-blog-frontend
    ports:
      - "80:80"
    volumes:
      - ./micro-blog_micro-blog-frontend:/app
    networks:
      - blogapp
    depends_on:
      - backend

  backend:
    build: 
      context: ./micro-blog_micro-blog-backend/backend
    ports:
      - "5000:5000"
    volumes:
      - ./micro-blog_micro-blog-backend/backend:/app
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_BLACKLIST_ENABLED=true
      - JWT_BLACKLIST_TOKEN_CHECKS=access,refresh
      - IMAGE_UPLOADS=uploads
      - JWT_ACCESS_TOKEN_EXPIRES=86400
    networks:
      - blogapp

networks:
  blogapp:
    driver: bridge
